/**
 * Math Basics Learning Syllabus for Students
 * Meta-catalog of the 10 educational sections with definitions, examples, and test targets.
 */

export const MATH_SECTIONS = [
  {
    id: 'addition',
    number: 1,
    title: 'Addition & Dénombrement',
    shortTitle: 'Addition (+)',
    badge: 'Base fondamentale',
    icon: '➕',
    description: 'Comprendre la fusion de deux quantités, la commutativité et l’élément neutre (0).',
    keyConcepts: [
      'L’addition combine deux ou plusieurs nombres pour trouver leur somme.',
      'Propriété commutative : a + b = b + a (ex: 7 + 5 = 5 + 7 = 12).',
      'Élément neutre : Ajouter 0 ne modifie pas le nombre (ex: 9 + 0 = 9).',
    ],
    sampleFormula: '25 + 17',
    expectedResult: '42',
    tip: 'Visualisez l’addition comme un déplacement vers la droite sur une droite numérique.',
  },
  {
    id: 'subtraction',
    number: 2,
    title: 'Soustraction & Différences',
    shortTitle: 'Soustraction (−)',
    badge: 'Différence & Écart',
    icon: '➖',
    description: 'Mesurer ce qui reste après avoir retiré une quantité ou calculer l’écart entre deux valeurs.',
    keyConcepts: [
      'La soustraction est l’opération inverse de l’addition (si a + b = c, alors c − b = a).',
      'Non-commutative : 10 − 4 ≠ 4 − 10.',
      'Soustraction de zéro : Tout nombre diminué de 0 reste inchangé (ex: 15 − 0 = 15).',
    ],
    sampleFormula: '100 − 37',
    expectedResult: '63',
    tip: 'Pour soustraire mentalement, arrondissez d’abord à la dizaine la plus proche.',
  },
  {
    id: 'multiplication',
    number: 3,
    title: 'Multiplication & Tables',
    shortTitle: 'Multiplication (×)',
    badge: 'Additions répétées',
    icon: '✖️',
    description: 'Accélérer les additions identiques, maîtriser les tables de 1 à 10 et les quadrillages.',
    keyConcepts: [
      'Multiplication = addition répétée (ex: 4 × 3 = 3 + 3 + 3 + 3 = 12).',
      'Élément absorbant (0) : Tout nombre multiplié par 0 vaut 0.',
      'Élément neutre (1) : Tout nombre multiplié par 1 reste lui-même.',
    ],
    sampleFormula: '12 × 8',
    expectedResult: '96',
    tip: 'Pour multiplier par 9, multipliez par 10 puis soustrayez le nombre une fois (ex: 7 × 9 = 70 − 7 = 63).',
  },
  {
    id: 'division',
    number: 4,
    title: 'Division & Partages',
    shortTitle: 'Division (÷)',
    badge: 'Partage équitable',
    icon: '➗',
    description: 'Partager équitablement une quantité, distinguer quotient et reste, et comprendre pourquoi diviser par zéro est impossible.',
    keyConcepts: [
      'La division sépare un nombre (dividende) en parts égales (diviseur) pour donner le quotient.',
      'Division par 0 impossible : Aucun nombre multiplié par 0 ne peut redonner un nombre non-nul.',
      'Relation euclidienne : Dividende = (Diviseur × Quotient) + Reste.',
    ],
    sampleFormula: '144 ÷ 12',
    expectedResult: '12',
    tip: 'Diviser par 2 revient à prendre la moitié ; diviser par 4 revient à prendre la moitié de la moitié.',
  },
  {
    id: 'fractions',
    number: 5,
    title: 'Fractions & Proportions',
    shortTitle: 'Fractions (a/b)',
    badge: 'Parties d’un tout',
    icon: '🍰',
    description: 'Représenter des portions d’unité, comprendre le rôle du numérateur et du dénominateur et simplifier.',
    keyConcepts: [
      'Numérateur (en haut) : Nombre de parts considérées.',
      'Dénominateur (en bas) : Nombre total de parts égales dans l’unité complète.',
      'Fractions équivalentes : 1/2 = 2/4 = 4/8 = 0,5.',
    ],
    sampleFormula: '3 ÷ 4',
    expectedResult: '0.75',
    tip: 'Pour additionner deux fractions, assurez-vous qu’elles ont le même dénominateur commun.',
  },
  {
    id: 'decimals',
    number: 6,
    title: 'Nombres Décimaux & Valeurs de Position',
    shortTitle: 'Décimaux (0,0)',
    badge: 'Précision fine',
    icon: '🎯',
    description: 'Comprendre la virgule, les dixièmes (0,1), centièmes (0,01) et millièmes (0,001).',
    keyConcepts: [
      'La virgule sépare la partie entière de la partie décimale fractionnaire.',
      'Chaque rang vers la droite est 10 fois plus petit que le précédent.',
      '0,1 + 0,2 = 0,3 : Notre moteur de calculatrice corrige automatiquement les artefacts de représentation binaire.',
    ],
    sampleFormula: '0.1 + 0.2',
    expectedResult: '0.3',
    tip: 'Alignez toujours les virgules les unes sous les autres lors d’une opération écrite sur papier.',
  },
  {
    id: 'percentages',
    number: 7,
    title: 'Pourcentages & Vie Quotidienne',
    shortTitle: 'Pourcentages (%)',
    badge: 'Base 100',
    icon: '🏷️',
    description: 'Calculer des remises, soldes, taxes et intérêts basés sur une échelle universelle de 100.',
    keyConcepts: [
      'Un pourcentage est une fraction dont le dénominateur est 100 (ex: 25% = 25/100 = 0,25).',
      'Calcul d’une remise : Prix réduit = Prix initial − (Prix initial × % / 100).',
      'Exemple rapide : 20% d’un nombre revient à diviser ce nombre par 5.',
    ],
    sampleFormula: '250 × 20 ÷ 100',
    expectedResult: '50',
    tip: 'Pour trouver 10% d’un nombre instantanément, décalez simplement la virgule d’un cran vers la gauche.',
  },
  {
    id: 'pemdas',
    number: 8,
    title: 'Ordre des Opérations (PEMDAS / BODMAS)',
    shortTitle: 'Priorités (PEMDAS)',
    badge: 'Règles de priorité',
    icon: '📐',
    description: 'Résoudre sans ambiguïté les expressions mixtes grâce à la hiérarchie officielle des opérations.',
    keyConcepts: [
      'P : Parenthèses en priorité absolue.',
      'E : Exposants et racines carrées.',
      'MD : Multiplications et Divisions (de gauche à droite).',
      'AS : Additions et Soustractions (de gauche à droite).',
    ],
    sampleFormula: '2 + 3 × 4',
    expectedResult: '14',
    tip: 'Dans 2 + 3 × 4, effectuez 3 × 4 = 12 d’abord, puis ajoutez 2 pour obtenir 14 (et non 20 !).',
  },
  {
    id: 'negatives',
    number: 9,
    title: 'Nombres Négatifs & Règle des Signes',
    shortTitle: 'Nombres Négatifs (±)',
    badge: 'Sous zéro',
    icon: '🧭',
    description: 'Manipuler les valeurs inférieures à zéro (températures, dettes) et appliquer les règles de multiplication des signes.',
    keyConcepts: [
      'Un nombre négatif est situé à gauche du zéro sur la droite numérique.',
      'Règle des signes en multiplication : (+) × (+) = (+), (−) × (−) = (+), (+) × (−) = (−).',
      'Soustraire un nombre négatif équivaut à ajouter son opposé positif : a − (−b) = a + b.',
    ],
    sampleFormula: '5 − 8',
    expectedResult: '-3',
    tip: 'Deux signes « moins » consécutifs se transforment en un signe « plus » : −(−5) = +5.',
  },
  {
    id: 'powers',
    number: 10,
    title: 'Puissances & Racines Carrées',
    shortTitle: 'Puissances (x² / √)',
    badge: 'Croissance exponentielle',
    icon: '⚡',
    description: 'Comprendre l’élévation à la puissance (carrés, cubes) et l’opération inverse qu’est la racine carrée.',
    keyConcepts: [
      'Puissance : aⁿ signifie que l’on multiplie le nombre a par lui-même n fois (ex: 5² = 5 × 5 = 25).',
      'Carré parfait : 1, 4, 9, 16, 25, 36, 49, 64, 81, 100, 121, 144.',
      'Racine carrée (√) : Nombre positif qui, élevé au carré, donne la valeur (ex: √49 = 7 car 7 × 7 = 49).',
    ],
    sampleFormula: '9 × 9',
    expectedResult: '81',
    tip: 'Tout nombre non-nul élevé à la puissance 0 vaut exactement 1 (ex: 7⁰ = 1).',
  },
];
